# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzySnek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
